import { revalidatePath } from "next/cache";
import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/admin-auth";
import { validateNewsPayload } from "@/lib/admin-content-validation";
import { databaseQuery } from "@/lib/postgres";
export const runtime="nodejs";interface Context{params:Promise<{id:string}>;}const select=`"id","createdAt","updatedAt","title","slug","excerpt","content","imageUrl","publishedAt","isPublished"`;
export async function GET(_:Request,{params}:Context){if(!(await isAdminAuthenticated()))return NextResponse.json({ok:false},{status:401});const rows=await databaseQuery(`SELECT ${select} FROM "News" WHERE "id"=$1 LIMIT 1`,[(await params).id]);return rows[0]?NextResponse.json({ok:true,item:rows[0]}):NextResponse.json({ok:false,message:"Новость не найдена."},{status:404});}
export async function PATCH(request:Request,{params}:Context){if(!(await isAdminAuthenticated()))return NextResponse.json({ok:false},{status:401});try{const value=validateNewsPayload(await request.json());if(!("data"in value))return NextResponse.json({ok:false,message:value.error},{status:400});const d=value.data!;const rows=await databaseQuery(`UPDATE "News" SET "updatedAt"=CURRENT_TIMESTAMP,"title"=$2,"slug"=$3,"excerpt"=$4,"content"=$5,"imageUrl"=$6,"publishedAt"=$7,"isPublished"=$8 WHERE "id"=$1 RETURNING ${select}`,[(await params).id,d.title,d.slug,d.excerpt,d.content,d.imageUrl,d.publishedAt?.toISOString()??null,d.isPublished]);if(!rows[0])return NextResponse.json({ok:false,message:"Новость не найдена."},{status:404});revalidatePath("/news");revalidatePath(`/news/${d.slug}`);return NextResponse.json({ok:true,item:rows[0]});}catch(error){if((error as{code?:string}).code==="23505")return NextResponse.json({ok:false,message:"Новость с таким slug уже существует."},{status:409});return NextResponse.json({ok:false,message:"Не удалось сохранить новость."},{status:500});}}
export async function DELETE(_:Request,{params}:Context){if(!(await isAdminAuthenticated()))return NextResponse.json({ok:false},{status:401});try{const rows=await databaseQuery<{id:string}>(`DELETE FROM "News" WHERE "id"=$1 RETURNING "id"`,[(await params).id]);if(!rows[0])return NextResponse.json({ok:false,message:"Новость не найдена."},{status:404});revalidatePath("/news");return NextResponse.json({ok:true});}catch{return NextResponse.json({ok:false,message:"Не удалось удалить новость."},{status:500});}}
