import { revalidatePath } from "next/cache";
import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/admin-auth";
import { validatePlayerPayload } from "@/lib/admin-content-validation";
import { createDatabaseId, neonQuery } from "@/lib/neon";
export const runtime="nodejs";
const select=`"id","createdAt","updatedAt","firstName","lastName","slug","birthDate","nationality","city","position","club","height","weight","preferredFoot","description","achievements","photoUrl","videoUrl","isPublished","sortOrder"`;
export async function GET(){if(!(await isAdminAuthenticated()))return NextResponse.json({ok:false},{status:401});try{return NextResponse.json({ok:true,players:await neonQuery(`SELECT ${select} FROM "Player" ORDER BY "sortOrder" ASC,"createdAt" DESC`)});}catch{return NextResponse.json({ok:false,message:"Не удалось загрузить игроков."},{status:500});}}
export async function POST(request:Request){if(!(await isAdminAuthenticated()))return NextResponse.json({ok:false},{status:401});try{const value=validatePlayerPayload(await request.json());if(!("data"in value))return NextResponse.json({ok:false,message:value.error},{status:400});const d=value.data!;const rows=await neonQuery(`INSERT INTO "Player" ("id","createdAt","updatedAt","firstName","lastName","slug","birthDate","nationality","city","position","club","height","weight","preferredFoot","description","achievements","photoUrl","videoUrl","isPublished","sortOrder") VALUES ($1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING ${select}`,[createDatabaseId(),d.firstName,d.lastName,d.slug,d.birthDate?.toISOString()??null,d.nationality,d.city,d.position,d.club,d.height,d.weight,d.preferredFoot,d.description,d.achievements,d.photoUrl,d.videoUrl,d.isPublished,d.sortOrder]);revalidatePath("/");revalidatePath("/players");return NextResponse.json({ok:true,player:rows[0]},{status:201});}catch(error){if((error as{code?:string}).code==="23505")return NextResponse.json({ok:false,message:"Игрок с таким slug уже существует."},{status:409});return NextResponse.json({ok:false,message:"Не удалось создать игрока."},{status:500});}}
