import { revalidatePath } from "next/cache";
import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/admin-auth";
import { validatePlayerPayload } from "@/lib/admin-content-validation";
import { databaseQuery } from "@/lib/postgres";
export const runtime="nodejs";interface Context{params:Promise<{id:string}>;}const select=`"id","createdAt","updatedAt","firstName","lastName","slug","birthDate","nationality","city","position","club","clubContractUntil","agencyContractUntil","height","weight","preferredFoot","description","achievements","photoUrl","videoUrl","isPublished","sortOrder"`;
export async function GET(_:Request,{params}:Context){if(!(await isAdminAuthenticated()))return NextResponse.json({ok:false},{status:401});const rows=await databaseQuery(`SELECT ${select} FROM "Player" WHERE "id"=$1 LIMIT 1`,[(await params).id]);return rows[0]?NextResponse.json({ok:true,player:rows[0]}):NextResponse.json({ok:false,message:"Игрок не найден."},{status:404});}
export async function PATCH(request:Request,{params}:Context){if(!(await isAdminAuthenticated()))return NextResponse.json({ok:false},{status:401});try{const value=validatePlayerPayload(await request.json());if(!("data"in value))return NextResponse.json({ok:false,message:value.error},{status:400});const d=value.data!;const rows=await databaseQuery(`UPDATE "Player" SET "updatedAt"=CURRENT_TIMESTAMP,"firstName"=$2,"lastName"=$3,"slug"=$4,"birthDate"=$5,"nationality"=$6,"city"=$7,"position"=$8,"club"=$9,"clubContractUntil"=$10,"agencyContractUntil"=$11,"height"=$12,"weight"=$13,"preferredFoot"=$14,"description"=$15,"achievements"=$16,"photoUrl"=$17,"videoUrl"=$18,"isPublished"=$19,"sortOrder"=$20 WHERE "id"=$1 RETURNING ${select}`,[(await params).id,d.firstName,d.lastName,d.slug,d.birthDate?.toISOString()??null,d.nationality,d.city,d.position,d.club,d.clubContractUntil?.toISOString()??null,d.agencyContractUntil?.toISOString()??null,d.height,d.weight,d.preferredFoot,d.description,d.achievements,d.photoUrl,d.videoUrl,d.isPublished,d.sortOrder]);if(!rows[0])return NextResponse.json({ok:false,message:"Игрок не найден."},{status:404});revalidatePath("/");revalidatePath("/players");revalidatePath(`/players/${d.slug}`);return NextResponse.json({ok:true,player:rows[0]});}catch(error){if((error as{code?:string}).code==="23505")return NextResponse.json({ok:false,message:"Игрок с таким slug уже существует."},{status:409});return NextResponse.json({ok:false,message:"Не удалось сохранить игрока."},{status:500});}}
export async function DELETE(_:Request,{params}:Context){if(!(await isAdminAuthenticated()))return NextResponse.json({ok:false},{status:401});try{const rows=await databaseQuery<{id:string}>(`DELETE FROM "Player" WHERE "id"=$1 RETURNING "id"`,[(await params).id]);if(!rows[0])return NextResponse.json({ok:false,message:"Игрок не найден."},{status:404});revalidatePath("/");revalidatePath("/players");return NextResponse.json({ok:true});}catch{return NextResponse.json({ok:false,message:"Не удалось удалить игрока."},{status:500});}}
